# Generated by Django 6.0.6 on 2026-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В процессе'), ('SHIPPED', 'Передан в доставку'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20),
        ),
    ]
